### ISSUE TITLE
Add a flag to support the insertion of the 'use strict' directive

### ISSUE THREAD

**Issue by RossVertizan** [axelpale/genversion#12]
As title really, some projects enforce the use of the 'use strict' directive and it would be beneficial to have genversion support this in the output.

I have already made the changes and will submit a pull request.

**Comment by axelpale** [comment]
Awesome! Thanks for the valuable addition. I will review the changes and the details you mentioned in PR as soon as I have time.

**Comment by RossVertizan** [comment]
Excellent. Thanks very much.

**Comment by axelpale** [comment]
Solved in v2.4.0
