### ISSUE TITLE
Add a flag to make the version output as double-quotes instead of single-quotes.

### ISSUE THREAD

**Issue by rhea-manuel** [axelpale/genversion#14]
Right now, genversion outputs the version in single quotes; it'd be nice for style reasons to have an option to output in double quotes instead (" instead of ').

**Comment by axelpale** [comment]
Thanks @rhea-manuel for the feature request. I have good news: the freshly-baked genversion v3.0.0 now has flags `-d, --double` to generate with double quotes instead of singles. In case you are using the API, set `useDoubleQuotes: true`. Let me know if you find any unexpected behavior.
