### ISSUE TITLE
git clone/checkout inserts CR characters causing --check-only to malfunction

### ISSUE THREAD

**Issue by krystalmonolith** [axelpale/genversion#15]
## Environment:
This issue only relates to genversion usage on Window OS. 

## Conditions for `--check-only` to malfunction:
This issue only occurs when the generated version source file is *recreated* when executing git commands such as `git clone` or `git checkout`. On Windows OS when the git configuration includes `core.autocrlf=true` git expands LF characters to CRLF when `git` creates or overwrites the generated version source file.

## Suggested Fix:
 Strip all CR character from the generated source file string *before* the `--check-only` validation of the file contents occurs.

## Linux/Mac Side Effects: 
AFAIK there are *no* side effects ... git does not expand LF to CRLF on Linux/Mac.

**Comment by axelpale** [comment]
Thanks for the reply; I can see it now. The flag might bring only more confusion because of git doing its things nevertheless.

Oh, that was a quick adoption :) Good to hear everything is in order. Thank you.
