### ISSUE TITLE
integrate with xo

### ISSUE THREAD

**Issue by ctranstrum** [axelpale/genversion#17]
I'm working in a project that is using [xo](https://www.npmjs.com/package/xo) for its code style, and want to add genversion to it, but xo complains about the file that genversion creates because xo wants all comments to start with a capital letter ...

Any chance you would consider updating genversion to either use a capital letter in its comment line by default or at least adding another command-line option to capitalize the comment?

**Comment by ctranstrum** [comment]
Yes, I had the same thoughts initially as well. A flag to customize the signature would let anyone get just what they needed.

But I also had the same concern as you about how many flags this very simple module already has, and I thought about the tradeoffs of having something hard-coded vs one more flag. In my opinion, 99.9% of the users of this module do not care what is actually in the signature line, and for people like me who are using a ridiculous style guide, we only care that the signature meets the requirements of the style guide.

Having a signature flag as you suggested would definitely meet my needs. But also, what if you just set the signature to begin with a capital letter and end with a period? I can't imagine any style guide complaining about the line at that point, and then there is no need to pollute the tool with options that aren't really necessary.

It's your package, and so your call, but I've updated my existing PR to include a period at the end of the hard-coded signature, in case you want to go that direction.

If you decide that the `--signature`, `-S` flag is the solution you'd prefer, just let me know, and I'd be happy to modify the PR to go that direction.

Thanks!

**Comment by axelpale** [comment]
I like your thinking. Will merge and release in 3.1.0.

**Comment by axelpale** [comment]
Released v3.1.0 with the signature `// Generated by genversion.`. I had to replace the hassle with startsWith and toLowerCase functions with a regular expression. Also wrote some unit tests to ensure the old lower case signature is handled properly.

Let me know if you experience any problems with v3.1.0. Thank you.

**Comment by ctranstrum** [comment]
Tested, and works perfectly! Much prefer your regex solution, nicely done. Thanks so much for your responsiveness on this.
